[package]
name = "bissection-rs"
version = "0.1.0"
authors = ["andrekorol <anrobits@yahoo.com.br>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
meval = "0.2.0"
text_io = "0.1.7"
